---

galaxy_info:
  author: zenoamaro
  description: A role to install and configure io.js and NPM.
  version: 0.2.0
  license: MIT
  min_ansible_version: 1.6

  platforms:

    - name: Debian
      versions:
        - jessie
        - sid

    - name: Ubuntu
      versions:
        - trusty

  categories:
    - web
    - development

dependencies: []
